services:
  verifier:
    build:
      context: .
      dockerfile: ./images/verifier.dockerfile
    container_name: verifier
    hostname: verifier
    ports:
      - 7676:7676
    healthcheck:
      test:
          - CMD
          - curl
          - -f
          - http://localhost:7676/health
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  deps:
    image: alpine
    command: ['echo', 'Dependencies running']
    depends_on:
        verifier:
            condition: service_healthy